### PR TITLE
BAH-2081 | Added db dumps for bahmni version 0.94

### PR DESCRIPTION
**Pull request by SooryaKumaranC-tw**

### CODE REVIEW

**Comment by N0-man** [comment]
Why maintain a fresh DB dump? a fresh DB can be bootstraped from the OMRS itself

**Comment by SooryaKumaranC-tw** [comment]
> Why maintain a fresh DB dump? a fresh DB can be bootstraped from the OMRS itself

Yes Nouman correct.  So the reason is:
- For metadata analysis of fresh and demo db we needed this dumb in place for latest bahmni 0.94. So that we can have this as a reference. 
- Also since openmrs is upgraded to 2.4.2 and also bahmni to 0.94 there were no related dumps in place for both demo and fresh db.

**Comment by binduak** [comment]
@N0-man We don't use the dumps/sql files that are uploaded to [bahmni-scripts](https://github.com/Bahmni/bahmni-scripts) repo in the distro. These dumps are mostly for community usage and for quick reference.

**Comment by SooryaKumaranC-tw** [comment]
As discussed, removing fresh db dump because fresh DB can bootstrap from the OMRS itself on start by setting **create_tables = true** and also allows to keep schema up to date by setting **auto_update_database = true** considering Bahmni running on Docker and Kubernates .

**Review by binduak — APPROVED** [review]

**Pull request merged**
